version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mobile_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wave2547
      POSTGRES_DB: mobile_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: